### ISSUE TITLE
Implement CreateUser function

### ISSUE THREAD

**Issue by caseywilliams** [Gilmore-PDX-CS/Group3#10]
Currently there is a `CreateUser()` function on the controller, but it does nothing. This function should do the following:

- Present a submenu (i.e. call a new function on the View) to determine whether the manager wants to create a Member, Provider, or Manager record, or cancel
- Based on this input, either cancel or call `View.CreateMember`, `View.CreateProvider`, or `View.CreateManager`.
- Print some sort of confirmation message showing the newly saved data.

**Comment by joel-lilja** [comment]
between mine and casey's work this is complete
