### ISSUE TITLE
Implement ViewUser function

### ISSUE THREAD

**Issue by caseywilliams** [Gilmore-PDX-CS/Group3#13]
There is no method in the controller for this yet, but we'll need to add one to complete our set of Create/Read/Update/Delete actions for managers. We'll need to add a new option to the menu for it and create a controller action that does the following:

- Present a submenu (i.e. call a new function on the View) to determine whether the manager wants to look up a Member, Provider, or Manager record, or cancel
- Based on this input, either show a prompt for the Member/Provider/Manager ID number or cancel
- Try to fetch the Member/Provider/Manager record from the database; If it doesn't exist, show the initial prompt again
- Once a record is found, print its information to the screen and return to the main menu.

**Comment by joel-lilja** [comment]
Currently implimenting

**Comment by joel-lilja** [comment]
Implemented
