### ISSUE TITLE
Implement Request Directory option

### ISSUE THREAD

**Issue by caseywilliams** [Gilmore-PDX-CS/Group3#14]
Currently there is a `RequestDirectory()` function in the controller, but it does nothing. When called, it should fetch all of the services available from the database and write a file containing a list of services to an output directory. Each service in the list should include the following:

- The name of the service
- The six-digit service code
- The fee for the service

The services in the list should be sorted alphabetically by service name. There is no spec about what to name the output file. Since the information will not change from run to run, I expect we can just name it e.g. `provider-directory.txt` and have subsequent calls to this function just overwrite that file.

**Comment by joel-lilja** [comment]
bens working on i believe

**Comment by bbruser885** [comment]
I believe I'm finished if you want to look over it
