### ISSUE TITLE
Pad integer IDs to the number of digits specified in the requirements doc

### ISSUE THREAD

**Issue by caseywilliams** [Gilmore-PDX-CS/Group3#16]
ChocAn spec says IDs should be padded, e.g. 9 digits for User ID numbers. Let's make sure every time we display values on screen or print them for the user, they're padded the right number of digits.

**Comment by joel-lilja** [comment]
Low priority i assume?

**Comment by atheron80** [comment]
I made a func called ConvertToUserId() that pads the Id number. I didn't check this off because I didn't have time to find all the places where we need to convert them.
