### ISSUE TITLE
Implement provider report function

### ISSUE THREAD

**Issue by caseywilliams** [Gilmore-PDX-CS/Group3#6]
To be implemented after #4. This function will be called from the single report submenu and the "run all reports" menu option.

Implement a function in the controller that looks through the database to find each provider who as given at least one consultation during the preceding week. Write one file for each of these providers in an output directory. Each of these files should contain the following information:

- The provider’s name (up to 25 characters).
- The provider’s ID number (9 digits).
- The provider’s street address (up to 25 characters).
- The provider’s city (up to 14 characters).
- The provider’s state (2 letters).
- The provider’s zip code (5 digits).
- A list of consultations that the provider gave at ChocAn during the preceding week, including the following information:
1. The date of service (MM-DD-YYYY).
2. The date and time the data was stored in the system (MM-DD-YYYY HH:MM:SS).
3. The receiving member’s name (up to 25 characters).
4. The receiving member’s ID number (9 digits).
5. The service code for the service provided (6 digits).
6. The fee to be billed for the consultation (up to $999.99).
- The total number of consultations given during the preceding week (under 999).
- The total fees billed for these consultations.

The filename should take the format `<provider name><date of report>.txt`.

**Comment by joel-lilja** [comment]
Implemented
