### ISSUE TITLE
ProviderDirectory Class

### ISSUE THREAD

**Issue by gilben1** [Gilmore-PDX-CS/Group3#6]

**Comment by spencer-hann** [comment]
I'm working on this.
I'm overriding toString() in lieu of the display function, since that's how displays are typically dealt with in Java

**Comment by spencer-hann** [comment]
I'm also taking care of the Service class because they're intertwined. also, adding Service.toString()

**Comment by spencer-hann** [comment]
ProviderDirectory class is done along with the Service class and I designed them so that the ProviderDirectoryTest class just tests both of them together
