### ISSUE TITLE
Implement AP summary function

### ISSUE THREAD

**Issue by caseywilliams** [Gilmore-PDX-CS/Group3#8]
To be implemented after #4. This function will be called from the single report submenu and the "run all reports" menu option.

Implement a function in the controller that looks through the database to find each provider who has given at least one consultation during the preceding week. Write a single file in an output directory. 
It should include the following information for each provider:

- The provider’s identity (There is no spec for what "identity" means; I assume ID number and name are sufficient)
- The total number of consultations the provider gave during the preceding week
- The total fees charged for these consultations

Additionally, it should include:

- The total number of providers who gave at least one consultation during the week
- The overall total fees charged across all providers for all consultations during the week.

There is no spec about the filename for the output, but maybe `ap<date of report>.txt` would do.

**Comment by joel-lilja** [comment]
Implemented
